### ISSUE TITLE
`new Pipeline()` results in "Invalid native pointer" exception

### ISSUE THREAD

**Issue by zilti** [gstreamer-java/gst1-java-core#118] opened 2018-10-31 12:40 UTC
OpenJDK 8. This exception seems to have no consistent way. GStreamer also suddenly complains about missing factories.

I call `new Pipeline()` right after calling `Gst.init("somename")`. When I try the same thing in a REPL, it works fine. Are there known things that interfere with gstreamer-java?

**Comment by neilcsmith-net** [comment] 2018-10-31 16:04
No, but there may be unknown things! :wink:

Can you give me a bit more information on your system?  OS, JNA version, GStreamer version, etc?

What are you doing when you see missing factories?  How are you setting up the paths for the native GStreamer libraries and plugins?

Do you get a stack trace with the exception?

When you say REPL do you mean `gst-launch`, etc. or JShell?

**Comment by zilti** [comment] 2018-10-31 16:59
GStreamer 1.14.4, OpenSUSE Tumbleweed with Kernel 4.18.15.

And I figured out what it is. Funnily, it compiled my test files as part of the main project, and it seems a call to `Gst#deinit` throws off the entire library, and even subsequent `Gst#init` calls can't get it back on track. Removing the `Gst.deinit()` calls "fixed" the problem.

**Comment by neilcsmith-net** [comment] 2018-10-31 18:52
@zilti so this is a duplicate of #70 then. Are you on the mailing list? [1]  It's been discussed there too recently.  Simply put, you do not want to call `Gst.deinit()`.  We may need to be much clearer about that.  It's there for API completeness, but should never really be used in application code - see https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gstreamer-Gst.html#gst-deinit  In particular you can't use `Gst.init()` after `Gst.deinit()`

[1] - https://groups.google.com/forum/#!forum/gstreamer-java

**Closed** 2018-10-31 18:53 UTC

**Comment by zilti** [comment] 2018-11-01 08:03
Oooh, no, I'm not on the mailing list. Thank you for the information.
